# Array Iterating

In [1]:
import numpy as np

In [ ]:
d1 = np.array([1,2,3,4])
d2 = np.array([[1,2,3],[4,5,6]])
d3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


In [6]:
for i in d1:
    print(i)

1
2
3
4


In [10]:
for i in d2:
    print(i)

for i in d2:
    for j in i:
        print(j,end=" ")

[1 2 3]
[4 5 6]
1 2 3 4 5 6 

In [11]:
for i in d3:
    print(i)

for i in d3:
    for j in i:
        for k in j:
            print(k,end=" ")

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 

## Iterating Arrays Using nditer()

In [12]:
# Iterating on Each Scalar Element
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
# Iterating Array With Different Data Types
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

# We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
# NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other 

# space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

b'1'
b'2'
b'3'


In [16]:
# Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::3]):
  print(x)

1
4
5
8


## Enumerated Iteration Using ndenumerate()


Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [17]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [18]:
# 2D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
