## NumPy ndarray Object

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray

In [6]:
arr = np.array((1,2,3,4))
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

In [7]:
# O-D array
arr_0 = np.array(28)
print(arr_0)
print(type(arr_0))

28
<class 'numpy.ndarray'>


In [8]:
# 1D array
arr_1 = np.array([1,2,3,4])
print(arr_1)
print(type(arr_1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
# 2D array
arr_2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2)
print(type(arr_2))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [11]:
#3D array
arr_3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr_3)
print(type(arr_3))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [17]:
# check dimentions

a = np.array(28)
b = np.array([1,2,3,4])
c = np.array([[1,2,3,4],[5,6,7,8]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim,"\n" ,b.ndim ,"\n",c.ndim, "\n" ,d.ndim)

0 
 1 
 2 
 3


# Higher Dimensional Arrays
An array can have any number of dimensions.
When the array is created, you can define the number of dimensions by using the ndmin argument.



In [18]:
arr_dim = np.array([1, 2, 3, 4], ndmin=5)

print(arr_dim)
print('number of dimensions :', arr_dim.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# Indexing


In [20]:
# 1D array indexing
print(b[1])

2


In [21]:
# 2D array indexing
print(c[1,2])

7


In [23]:
#3D array indexing
print(d[0,1,2])

6


In [25]:
# Negative Indexing
print(c[1,-1])

8
