In [1]:
import numpy as np

# COPY:

In [3]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# VIEW:


In [6]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

# The view SHOULD be affected by the changes made to the original array.

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# we can make Changes in the VIEW:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 33

print(arr)
print(x)

[33  2  3  4  5]
[33  2  3  4  5]


In [ ]:
# Check if Array Owns its Data

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[33  2  3  4  5]
