# NumPy Joining Array

in NumPy we join arrays by axes

In [1]:
import numpy as np

In [5]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

con = np.concatenate((a1,a2))
print(con)

[1 2 3 4 5 6 7 8]


In [12]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a2 = np.array([[8,7,6,5],[4,3,2,1]])

con = np.concatenate((a1,a2),axis=1)
print(con)

[[1 2 3 4 8 7 6 5]
 [5 6 7 8 4 3 2 1]]


## Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [13]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

con = np.stack((a1,a2))
print(con)

[[1 2 3 4]
 [5 6 7 8]]


Stacking Along Rows
NumPy provides a helper function: hstack() to stack along rows.

In [14]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

con = np.hstack((a1,a2))
print(con)

[1 2 3 4 5 6 7 8]


Stacking Along Columns
NumPy provides a helper function: vstack()  to stack along columns.

In [15]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

con = np.vstack((a1,a2))
print(con)

[[1 2 3 4]
 [5 6 7 8]]


Stacking Along Height (depth)
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [16]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

con = np.dstack((a1,a2))
print(con)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
